---

- name: Ensure Java is installed.
  package:
    name: "java-1.8.0-openjdk"
    state: present
    
- name: tomcat | group add
  group: name=tomcat
    
- name: tomcat | user add
  user: name=tomcat group=tomcat home=/opt/tomcat createhome=no 
  
    #télécharger l'archive de tomcat
- name: tomcat | binary download
  get_url: url="http://mirror.nus.edu.sg/apache/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz"  dest="/tmp"
   

- name: tomcat  | extract archive
    #unarchive le dossier .tar
  shell: "tar xzf /tmp/apache-tomcat-8.5.40.tar.gz -C /opt"

    #création d'un lien symbolique de tomcat
- name: tomcat  | symlink install directory
  file: src="/opt/apache-tomcat-8.5.40" path="/opt/tomcat8" state=link
  

- name: tomcat  |   change ownership of target installation
  file: path="/opt/tomcat8" owner=tomcat group=tomcat state=directory recurse=yes
- name: tomcat  | systemd
  template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service
- name: tomcat  | restart
  service:
     name: tomcat
     state: restarted

- name: envoie de fichier war
  copy:
      src: sample.war
      dest: /opt/tomcat8/webapps
      owner: tomcat
      group: tomcat
      mode: u=rwx,g=rx,o=r

- name: Ensure application is deployed
  stat: 
      path: /opt/tomcat8/webapps/sample

- name: Check that you can connect (GET) to a sample app welcome page and it returns a status 200 before continue
  uri:
     url: http://localhost:8080/sample/index.html
  register: result
  until: result.status == 200
  retries: 10
  delay: 10

- name : Affiche la variable result
  debug:
      var: result
    
   
